name: Alpha vantage .NET build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [ ubuntu-latest ]
    strategy:
        matrix:
          os: [ ubuntu-latest, windows-latest]
      
    defaults:
      run:
        working-directory: src

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run:
        dotnet restore ../AlphaVantage.sln
        
    - name: Build solution
      run:
        dotnet build ../AlphaVantage.sln --configuration Release --no-restore
        
    - name: Test
      run:
        dotnet test ../AlphaVantage.sln --configuration Release --no-build --verbosity normal
