name: alpha vantage .NET workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [ ubuntu-latest ]
    defaults:
      run:
        working-directory: src

    steps:
    - uses: actions/checkout@v2
    - name: Setup alpha vantage .NET workflow
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore AlphaVantage
    - name: Build
      run: dotnet build AlphaVantage --no-restore
    - name: Test
      run: dotnet test ../test/AlphaVantage.Test --no-build --verbosity normal
